import React, { useState } from 'react';
import { ChevronDown, ChevronUp, Shield, Lock, Eye, Users, FileText, Phone, Mail, MapPin } from 'lucide-react';

const PrivacyPolicy = () => {
  const [expandedSection, setExpandedSection] = useState(null);

  const toggleSection = (section) => {
    setExpandedSection(expandedSection === section ? null : section);
  };

  const sections = [
    {
      id: 'interpretation-definitions',
      title: 'Interpretation and Definitions',
      icon: <FileText className="w-5 h-5" />,
      content: (
        <div className="space-y-4">
          <div>
            <h4 className="font-semibold text-[var(--dashboard-text)] mb-2">Interpretation</h4>
            <p className="text-[var(--dashboard-text-muted)] mb-4">
              The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>
          </div>
          <div>
            <h4 className="font-semibold text-[var(--dashboard-text)] mb-2">Definitions</h4>
            <p className="text-[var(--dashboard-text-muted)] mb-3">For the purposes of this Privacy Policy:</p>
            <ul className="list-disc pl-6 space-y-2 text-[var(--dashboard-text-muted)]">
              <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
              <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Medoraa.</li>
              <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
              <li><strong>Country</strong> refers to: Uttar Pradesh, India</li>
              <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong> refers to the Website.</li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
              <li><strong>Website</strong> refers to Medoraa, accessible from <a href="https://www.medoraa.co.in/" target="_blank" rel="noopener noreferrer" className="text-[var(--dashboard-primary)] hover:underline">https://www.medoraa.co.in/</a></li>
              <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>
          </div>
        </div>
      )
    },
    {
      id: 'data-collection',
      title: 'Collecting and Using Your Personal Data',
      icon: <Users className="w-5 h-5" />,
      content: (
        <div className="space-y-4">
          <div>
            <h4 className="font-semibold text-[var(--dashboard-text)] mb-2">Types of Data Collected</h4>
            
            <div className="mb-4">
              <h5 className="font-medium text-[var(--dashboard-text)] mb-2">Personal Data</h5>
              <p className="text-[var(--dashboard-text-muted)] mb-2">
                While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
              </p>
              <ul className="list-disc pl-6 space-y-1 text-[var(--dashboard-text-muted)]">
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Address, State, Province, ZIP/Postal code, City</li>
                <li>Usage Data</li>
              </ul>
            </div>

            <div className="mb-4">
              <h5 className="font-medium text-[var(--dashboard-text)] mb-2">Usage Data</h5>
              <p className="text-[var(--dashboard-text-muted)] mb-2">
                Usage Data is collected automatically when using the Service.
              </p>
              <p className="text-[var(--dashboard-text-muted)] mb-2">
                Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
              </p>
              <p className="text-[var(--dashboard-text-muted)]">
                When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
              </p>
            </div>
          </div>
        </div>
      )
    },
    {
      id: 'tracking-cookies',
      title: 'Tracking Technologies and Cookies',
      icon: <Eye className="w-5 h-5" />,
      content: (
        <div className="space-y-4">
          <p className="text-[var(--dashboard-text-muted)]">
            We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
          </p>
          
          <div>
            <h4 className="font-semibold text-[var(--dashboard-text)] mb-2">Types of Cookies We Use</h4>
            <ul className="list-disc pl-6 space-y-3 text-[var(--dashboard-text-muted)]">
              <li>
                <strong>Necessary / Essential Cookies</strong><br/>
                <span className="text-sm">Type: Session Cookies - These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features.</span>
              </li>
              <li>
                <strong>Cookies Policy / Notice Acceptance Cookies</strong><br/>
                <span className="text-sm">Type: Persistent Cookies - These Cookies identify if users have accepted the use of cookies on the Website.</span>
              </li>
              <li>
                <strong>Functionality Cookies</strong><br/>
                <span className="text-sm">Type: Persistent Cookies - These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference.</span>
              </li>
            </ul>
          </div>
        </div>
      )
    },
    {
      id: 'data-usage',
      title: 'Use of Your Personal Data',
      icon: <Lock className="w-5 h-5" />,
      content: (
        <div className="space-y-4">
          <p className="text-[var(--dashboard-text-muted)] mb-4">
            The Company may use Personal Data for the following purposes:
          </p>
          
          <ul className="list-disc pl-6 space-y-2 text-[var(--dashboard-text-muted)]">
            <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
            <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
            <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.</li>
            <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
            <li><strong>To provide You</strong> with news, special offers and general information about other goods, services and events which we offer.</li>
            <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
            <li><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
            <li><strong>For other purposes:</strong> We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns.</li>
          </ul>

          <div className="mt-6">
            <h4 className="font-semibold text-[var(--dashboard-text)] mb-2">Information Sharing</h4>
            <p className="text-[var(--dashboard-text-muted)] mb-2">We may share Your personal information in the following situations:</p>
            <ul className="list-disc pl-6 space-y-1 text-[var(--dashboard-text-muted)]">
              <li><strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service.</li>
              <li><strong>For business transfers:</strong> We may share or transfer Your personal information in connection with any merger, sale of Company assets, financing, or acquisition.</li>
              <li><strong>With Affiliates:</strong> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy.</li>
              <li><strong>With business partners:</strong> We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
              <li><strong>With Your consent:</strong> We may disclose Your personal information for any other purpose with Your consent.</li>
            </ul>
          </div>
        </div>
      )
    },
    {
      id: 'data-retention',
      title: 'Retention and Transfer of Your Personal Data',
      icon: <FileText className="w-5 h-5" />,
      content: (
        <div className="space-y-4">
          <div>
            <h4 className="font-semibold text-[var(--dashboard-text)] mb-2">Data Retention</h4>
            <p className="text-[var(--dashboard-text-muted)] mb-2">
              The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
            </p>
            <p className="text-[var(--dashboard-text-muted)]">
              The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service.
            </p>
          </div>

          <div>
            <h4 className="font-semibold text-[var(--dashboard-text)] mb-2">Data Transfer</h4>
            <p className="text-[var(--dashboard-text-muted)] mb-2">
              Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction.
            </p>
            <p className="text-[var(--dashboard-text-muted)]">
              The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place.
            </p>
          </div>
        </div>
      )
    },
    {
      id: 'user-rights',
      title: 'Your Rights & Data Security',
      icon: <Shield className="w-5 h-5" />,
      content: (
        <div className="space-y-4">
          <div>
            <h4 className="font-semibold text-[var(--dashboard-text)] mb-2">Delete Your Personal Data</h4>
            <p className="text-[var(--dashboard-text-muted)] mb-2">
              You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
            </p>
            <p className="text-[var(--dashboard-text-muted)] mb-2">
              You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information.
            </p>
            <p className="text-[var(--dashboard-text-muted)]">
              Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.
            </p>
          </div>

          <div>
            <h4 className="font-semibold text-[var(--dashboard-text)] mb-2">Security of Your Personal Data</h4>
            <p className="text-[var(--dashboard-text-muted)]">
              The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
            </p>
          </div>

          <div>
            <h4 className="font-semibold text-[var(--dashboard-text)] mb-2">Disclosure Requirements</h4>
            <p className="text-[var(--dashboard-text-muted)] mb-2">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
            <ul className="list-disc pl-6 space-y-1 text-[var(--dashboard-text-muted)]">
              <li>Comply with a legal obligation</li>
              <li>Protect and defend the rights or property of the Company</li>
              <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
              <li>Protect the personal safety of Users of the Service or the public</li>
              <li>Protect against legal liability</li>
            </ul>
          </div>
        </div>
      )
    },
    {
      id: 'additional-policies',
      title: 'Additional Policies',
      icon: <Users className="w-5 h-5" />,
      content: (
        <div className="space-y-4">
          <div>
            <h4 className="font-semibold text-[var(--dashboard-text)] mb-2">Children's Privacy</h4>
            <p className="text-[var(--dashboard-text-muted)] mb-2">
              Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
            </p>
            <p className="text-[var(--dashboard-text-muted)]">
              If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.
            </p>
          </div>

          <div>
            <h4 className="font-semibold text-[var(--dashboard-text)] mb-2">Links to Other Websites</h4>
            <p className="text-[var(--dashboard-text-muted)] mb-2">
              Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
            </p>
            <p className="text-[var(--dashboard-text-muted)]">
              We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
            </p>
          </div>

          <div>
            <h4 className="font-semibold text-[var(--dashboard-text)] mb-2">Changes to this Privacy Policy</h4>
            <p className="text-[var(--dashboard-text-muted)] mb-2">
              We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
            </p>
            <p className="text-[var(--dashboard-text-muted)]">
              You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
            </p>
          </div>
        </div>
      )
    }
  ];

  return (
    <div style={{
      '--dashboard-primary': '#2c5f41',
      '--dashboard-secondary': '#2c5f41',
      '--dashboard-light': '#e8f5f5',
      '--dashboard-dark': '#145252',
      '--dashboard-text': '#1a2e2e',
      '--dashboard-text-muted': '#6b7280',
      '--dashboard-warning': '#ffa726',
      '--dashboard-danger': '#ef4444',
      '--dashboard-shadow': 'rgba(26, 95, 95, 0.15)',
      '--dashboard-shadow-light': 'rgba(26, 95, 95, 0.08)',
      '--dashboard-radius': '20px',
      '--dashboard-radius-sm': '12px',
      '--dashboard-transition': '0.3s ease'
    }} className="privacy-policy-container py-8 px-4">
      <style jsx>{`
        .privacy-policy-container {
          background: linear-gradient(135deg, #f8fffe 0%, #e8f5f5 100%);
          min-height: 100vh;
        }

        .privacy-header {
          background: linear-gradient(135deg, var(--dashboard-primary) 0%, var(--dashboard-dark) 100%);
          color: white;
          padding: 3rem 2rem;
          border-radius: var(--dashboard-radius);
          box-shadow: 0 10px 40px var(--dashboard-shadow);
          margin-bottom: 2rem;
        }

        .header-shield-icon {
          background: rgba(255, 255, 255, 0.2);
          backdrop-filter: blur(10px);
        }

        .principle-card {
          background: white;
          border-radius: var(--dashboard-radius);
          padding: 2rem;
          box-shadow: 0 8px 32px var(--dashboard-shadow-light);
          border: 1px solid rgba(44, 95, 65, 0.1);
        }

        .principle-icon-1 {
          background: linear-gradient(135deg, #4ade80 0%, #16a34a 100%);
          color: white;
        }

        .principle-icon-2 {
          background: linear-gradient(135deg, #60a5fa 0%, #3b82f6 100%);
          color: white;
        }

        .principle-icon-3 {
          background: linear-gradient(135deg, #a78bfa 0%, #8b5cf6 100%);
          color: white;
        }

        .text-gradient-blue {
          background: linear-gradient(135deg, #3b82f6 0%, #1e40af 100%);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
        }

        .text-gradient-green {
          background: linear-gradient(135deg, var(--dashboard-primary) 0%, var(--dashboard-dark) 100%);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
        }

        .text-gradient-purple {
          background: linear-gradient(135deg, #8b5cf6 0%, #7c3aed 100%);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
        }

        .section-card {
          background: white;
          border-radius: var(--dashboard-radius);
          box-shadow: 0 4px 20px var(--dashboard-shadow-light);
          border: 1px solid rgba(44, 95, 65, 0.1);
          transition: all var(--dashboard-transition);
          overflow: hidden;
        }

        .section-card:hover {
          transform: translateY(-2px);
          box-shadow: 0 8px 32px var(--dashboard-shadow);
        }

        .section-header {
          background: linear-gradient(90deg, rgba(44, 95, 65, 0.02) 0%, transparent 100%);
          border: none;
          transition: all var(--dashboard-transition);
        }

        .section-header:hover {
          background: linear-gradient(90deg, rgba(44, 95, 65, 0.05) 0%, transparent 100%);
        }

        .section-icon-1 {
          background: linear-gradient(135deg, #fbbf24 0%, #f59e0b 100%);
          color: white;
        }

        .section-icon-2 {
          background: linear-gradient(135deg, #34d399 0%, #10b981 100%);
          color: white;
        }

        .section-icon-3 {
          background: linear-gradient(135deg, #60a5fa 0%, #3b82f6 100%);
          color: white;
        }

        .section-icon-4 {
          background: linear-gradient(135deg, #f87171 0%, #ef4444 100%);
          color: white;
        }

        .section-icon-5 {
          background: linear-gradient(135deg, #a78bfa 0%, #8b5cf6 100%);
          color: white;
        }

        .section-icon-6 {
          background: linear-gradient(135deg, #fb7185 0%, #e11d48 100%);
          color: white;
        }

        .section-icon-7 {
          background: linear-gradient(135deg, #22d3ee 0%, #06b6d4 100%);
          color: white;
        }

        .section-content {
          border-top: 1px solid rgba(44, 95, 65, 0.1);
          background: linear-gradient(180deg, rgba(44, 95, 65, 0.01) 0%, transparent 100%);
        }

        .contact-card {
          background: linear-gradient(135deg, #f8fafc 0%, #e2e8f0 100%);
          border-radius: var(--dashboard-radius);
          box-shadow: 0 8px 32px var(--dashboard-shadow-light);
          border: 1px solid rgba(44, 95, 65, 0.1);
        }

        .contact-item {
          color: var(--dashboard-primary);
        }

        .privacy-footer {
          text-align: center;
          margin-top: 3rem;
          padding-top: 2rem;
          border-top: 1px solid rgba(44, 95, 65, 0.1);
        }

        .warning-box {
          background: linear-gradient(135deg, rgba(255, 167, 38, 0.1) 0%, rgba(255, 167, 38, 0.05) 100%);
          border-left: 4px solid var(--dashboard-warning);
        }
      `}</style>

      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="privacy-header text-center mb-12">
          <div className="header-shield-icon inline-flex items-center justify-center w-20 h-20 rounded-full mb-6">
            <Shield className="w-10 h-10 text-white" />
          </div>
          <h1 className="text-4xl font-bold mb-4">Privacy Policy</h1>
          <p className="text-lg text-white/90 max-w-2xl mx-auto">
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
          </p>
          <div className="mt-6 text-sm text-white/80">
            Last updated: July 27, 2025
          </div>
        </div>

        {/* Key Principles */}
        <div className="principle-card mb-8">
          <h2 className="text-2xl font-bold text-[var(--dashboard-text)] mb-6 text-gradient-blue">Our Privacy Principles</h2>
          <div className="grid md:grid-cols-3 gap-6">
            <div className="text-center">
              <div className="principle-icon-1 w-12 h-12 rounded-full flex items-center justify-center mx-auto mb-4">
                <Lock className="w-6 h-6" />
              </div>
              <h3 className="font-semibold text-[var(--dashboard-text)] mb-2">Secure by Design</h3>
              <p className="text-sm text-[var(--dashboard-text-muted)]">Your data is protected with commercially acceptable security measures and encryption.</p>
            </div>
            <div className="text-center">
              <div className="principle-icon-2 w-12 h-12 rounded-full flex items-center justify-center mx-auto mb-4">
                <Eye className="w-6 h-6" />
              </div>
              <h3 className="font-semibold text-[var(--dashboard-text)] mb-2">Transparent Control</h3>
              <p className="text-sm text-[var(--dashboard-text-muted)]">You have complete visibility and control over how your information is collected and used.</p>
            </div>
            <div className="text-center">
              <div className="principle-icon-3 w-12 h-12 rounded-full flex items-center justify-center mx-auto mb-4">
                <Users className="w-6 h-6" />
              </div>
              <h3 className="font-semibold text-[var(--dashboard-text)] mb-2">Purpose-Driven</h3>
              <p className="text-sm text-[var(--dashboard-text-muted)]">We only collect and use data necessary to provide and improve our healthcare services.</p>
            </div>
          </div>
        </div>

        {/* Expandable Sections */}
        <div className="space-y-4">
          {sections.map((section, index) => (
            <div key={section.id} className="section-card">
              <button
                onClick={() => toggleSection(section.id)}
                className="section-header w-full p-6 text-left flex items-center justify-between"
              >
                <div className="flex items-center space-x-4">
                  <div className={`section-icon-${index + 1} w-10 h-10 rounded-full flex items-center justify-center`}>
                    {section.icon}
                  </div>
                  <h3 className="text-xl font-semibold text-[var(--dashboard-text)]">{section.title}</h3>
                </div>
                {expandedSection === section.id ? (
                  <ChevronUp className="w-5 h-5 text-[var(--dashboard-text-muted)]" />
                ) : (
                  <ChevronDown className="w-5 h-5 text-[var(--dashboard-text-muted)]" />
                )}
              </button>
              {expandedSection === section.id && (
                <div className="section-content px-6 pb-6">
                  <div className="pt-6">
                    {section.content}
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>

        {/* Contact Information */}
        <div className="contact-card p-8 mt-8">
          <h2 className="text-2xl font-bold text-[var(--dashboard-text)] mb-6 text-gradient-green">Contact Us</h2>
          <p className="text-[var(--dashboard-text-muted)] mb-6">
            If you have any questions about this Privacy Policy, you can contact us:
          </p>
          <div className="flex items-center space-x-3">
            <Mail className="w-5 h-5 text-[var(--dashboard-primary)]" />
            <div>
              <div className="font-medium text-[var(--dashboard-text)]">Email</div>
              <div className="text-sm text-[var(--dashboard-text-muted)]">team@medoraa.co.in</div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="privacy-footer">
          <p className="text-sm text-gradient-purple">
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
          </p>
          <p className="text-sm mt-2 text-[var(--dashboard-text-muted)]">
            © 2025 Medoraa. All rights reserved.
          </p>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
